# ---------------------- ChatGuard 7.0 default configuration file --------------------- #
# Dont worry if you have just updated plugin. Old configuration saved as old_config.yml #
#        Please read comments and dont ask silly questions about configuration          #
#   Dont use Notepad++ default tabulation. Enable 'Replace by space' in Tab Settings    #
# ------------------------------------------------------------------------------------- #

# dont touch this
Version: 6

Check for updates: false

# NOTICE: Enabling Hard Mode enables message cancelling automatically 
# experimental function
Hard mode: false

# Max warnings and custom replacement work only if Separated warnings are enabled
swear settings:
    enabled: true
    inform admins: true
    max warnings: 3
    # supports color codes
    custom replacement: '<мат>'
caps settings:
    enabled: true
    inform admins: true
    max warnings: 3
    max caps percent: 70
    # dont check if message smaller than your value(ex. for escaping smiles)
    min message lenght: 3
flood settings:
    # flood messages will be cancelled in any way
    enabled: true
    inform admins: true
    max warnings: 3
    # in seconds
    flood time: 10
    # set to 0 to disable function
    message cooldown: 0
    # 1 value means that the last player's message will be checked for flood only(2 - with penultimate, etc.)
    flood levels: 1
spam settings:
    enabled: true
    inform admins: true
    max warnings: 3
    custom replacement: '<спам>'
    # set how many numbers can players send in one message, 0 - disable
    max numbers: 0
Messages:
    # bad words and spam will be replaced with appropriate replacement if disabled
    cancel if violation: true
    # works only if separated warnings are enabled
    replacement: '<цензура>'
    enable character whitelist: true
Warnings settings:
    enabled: true
    separate: true
    # works only if separate is false
    max count: 10
Punishment settings:
    # execute commands from commands section if player gains max warning count
    enabled: true
    # max mute time for native /cg mute command(set to 0 for unlimited). Time format - 1s, 1m, 1h, 1d
    max mute time: 1d
    # you can add any reason with any name how many as you want(but for what?)
    reasons: 
        swear: 'мат'
        msg-swear: 'Матершинник &6{Player} &aполучил мут!'
        caps: 'капс'
        msg-caps: 'Спамер &6{Player} &aполучил мут.'
        spam: 'спам'
        msg-spam: 'Спамер &6{Player} &aполучил мут.'
        flood: 'флуд'
        msg-flood: 'Флудер &6{Player} &aполучил мут.'
        mute-time: '30m'
    commands:
        custom: true
        # common commands will be executed if custom is false, you can use any reason described in reasons section
        # just use {Reason_(name)} tag
        common commands:
            #- cg mute {Player} {Reason_mute-time}
        swear commands:
            #- cg mute {Player} {Reason_mute-time} {Reason_swear}
            #- kill {Player}
            #- broadcast {Reason_msg-swear}
        caps commands:
            #- cg mute {Player} {Reason_mute-time} {Reason_caps}
            #- broadcast {Reason_msg-caps}
        flood commands:
            #- cg mute {Player} {Reason_mute-time} {Reason_flood}
            #- broadcast {Reason_msg_msg-flood}
        spam commands:
            #- cg mute {Player} {Reason_mute-time} {Reason_spam}
            #- broadcast {Reason_msg-spam}
# replace first element with second element in messages
Substitutions:
#- 'green|red'
Other settings:
    check signs: true
    check items: false
    # check player's command for swearing, capsing and flooding
    # to disable this set value to []. Number after colon means how many arguements in command we should skip
    check commands: ['/me:0', '/msg:1', '/t:1', '/tell:1', '/w:1', '/r:0', '/m:1', '/clan:1', '/cm:0']
    # may be useful if you find a bug and want report it to developer
    debug level: 0
    # if traditional messages listening system doesnt work(or smth else) plugin can listen packets
    use packets: false
    # works only if packet listening is disabled
    # available priorities HIGHEST, HIGH, NORMAL, LOW, LOWEST, MONITOR(not recommended to use)
    event priority: HIGHEST
    # Type plugin integration name to disable it if you have issues with it
    # Names - AuthMe34, AuthMe5, AuthMeLegacy, NoCheatPlus
    disabled integrations: []
